public with sharing class TestForBlog {
public contact contact{get;set;}
    public TestForBlog(ApexPages.StandardController controller) {

    }


    public String getContact() {
        return null;
    }


    public String getSomeString() {
        return null;
    }

// public string somestring;
    public string setSomeString(string s) {
        return null;
    }


    public PageReference SomeFunction() {
        return null;
    }
    

}